### ISSUE TITLE
2022/11/20 TODOs

### ISSUE THREAD

**Issue by KCFindstr** [RabiMimi/RabiRiichi#51]
- [x] Store game config in logs
- [x] Create a more complicated log for frontend debugging
- [x] (UI) Implement KaKan

**Comment by Frenqy** [comment]
加杠UI跟别的鸣牌UI不是共用的吗

**Comment by KCFindstr** [comment]
乐 我发现我的TileLayout不支持把一个牌横着放在另一个上面
